### PR TITLE
Current WIP

### PR DESCRIPTION
**Pull request by tommargar**
1. I've added all most bad thought traits like prosthophope, greedy, jealous.
2. Changed some triggers like "Sick" to the thoughts instead of calculating hediffs.
3. Made new textures for existing and new mood swings
4. added German translation (incomplete)
5. to do: check if all new options appear in the menu,; add translations in the xml files (DE, EN, RU atm)
6. maybe switch to CCL, I read they have a color picker, could be integrated in the options for color groups, like warning, alert, info etc.
7. old icons need to be updated or removed; the text icons could be accomplished with real text overlay, advantage would be to go multilingual stead of 30+ icons

Please don't release widely in its current state, still needs some work and tweaking. Also I'd like make a complete overhaul of the icons, maybe do a circle version.

### CODE REVIEW

**Comment by VaderTi** [comment]
Thanks for the help! I think that can only Promenade icons and text only, everything else must be removed. Just think to reduce the number of settings, they are too many, and the user does not need, and most importantly ease of minimaliz.
If the transition to CCL will expand the functionality of mod, it is a good idea.
I'll now 5 and possibly 7.

**Comment by tommargar** [comment]
Settings can be hidden, I prefer to keep them. I will add more icons in the next days in my fork.

**Comment by VaderTi** [comment]
In the last update I added all the statuses that you have created and added them to the settings menu. Just made some code optimization.

**Comment by tommargar** [comment]
Some changes broke the mod unfortunately. 
Removing the NotifyLog(ex) made the "cast from to" bug only invisible, not all stats in were updated and the mod ceased to work. Also the menu wasn't working properly after switching the load settings from xml sequence. I reverted most changes in my code because other things were not working any more.

I now made most of the status colors as own its own color and will try to integrate the CCL color picker.
For the moving to CCL mod menu, I can't figure out how to write this. Will make it as last.

**Comment by VaderTi** [comment]
I believe that first you need to modify the functionality, but only after a deal with bugs.
I've already thought about integration CCL in mod and have come to believe that this is necessary. I could add the necessary functionality.

**Comment by tommargar** [comment]
I have two bugs ATM, the "cannot cast from to" error, the call of the hediffdef causes this when getting the immunity. And in the added thoughtdefs room stats & pain, the list also sometimes has 0 contents and throws an exception. Those bugs need to be fixed, otherwise the updatecoloniststats can't continue.

I stopped looking in CCL. Too complicated for me. Advantages of CCL are the ColorPicker which should be rather easy to integrate, and the use of the ModMenu which is a lot of work if the dialogmenu contents are moved.

**Pull request closed without merging**
